In [2]:
import numpy as np
# 1: Array creation and manipulation

In [20]:
# Create a NumPy array of shape 5x5 filled with random int in [1,10]
A = np.random.randint(1,11, size=(5,5))
print(A)

[[ 3  6  8  1  4]
 [ 8  6  6  3  3]
 [10  4  5  8  1]
 [10  4  9  4  8]
 [ 9  1  8  3  3]]


In [21]:
# Extract second row, third column and the diagonal elements
second_row = A[1, :]
third_column = A[:, 2]
diagonal = np.diag(A)

In [22]:
# Reshape it into a 1D array of shape 1x25
A.reshape((1,25))

array([[ 3,  6,  8,  1,  4,  8,  6,  6,  3,  3, 10,  4,  5,  8,  1, 10,
         4,  9,  4,  8,  9,  1,  8,  3,  3]])

In [3]:
# 2: Linear algebra operations
# Generate two 3x3 matrices with random integers from 1 to 10
B = np.random.randint(1,11, size=(3,3))
C = np.random.randint(1,11, size=(3,3))

# Perform element-wise and matrix-matrix multiplication
print(f"Element wise product = {B * C}")
print(f"Matrix product = {B @ C}")
# or np.dot(B,C)

Element wise product = [[36 16 56]
 [ 5 16 42]
 [ 8 63 30]]
Matrix product = [[ 47  95  77]
 [ 56  99  85]
 [ 89 150 136]]


In [4]:
# Create a 3x3 matrix with random values, compute its inverse and det
D = np.random.rand(3,3)
print(f"Inverse: {np.linalg.inv(D)}")
print(f"Determinant: {np.linalg.det(D)}")

Inverse: [[ 2.49722447 -0.06084252 -2.48848266]
 [-0.84009663 -0.62965108  2.46714428]
 [-1.67356799  1.96107099 -0.00942222]]
Determinant: -0.19632283141048934


In [6]:
# 3: Statistical analysis
# Generate a 1D NumPy array with 20 random integers between 1 and 100
random_array = np.random.randint(1,101,20)
# Calculate mean, median, standard deviation and variance
print(f"Mean: {np.mean(random_array)}")
print(f"Median: {np.median(random_array)}")
print(f"Standard deviation: {np.std(random_array)}")
print(f"Variance: {np.var(random_array)}")

Mean: 48.55
Median: 51.0
Standard deviation: 27.335828138177924
Variance: 747.2475
